### ISSUE TITLE
Error running action

### ISSUE THREAD

**Issue by yoavain** [rlespinasse/git-commit-data-action#11]
I'm getting the following error after updating to the latest version (1.1.1)

```
Run rlespinasse/git-commit-data-action@1.1.1
Started: bash /home/runner/work/_actions/rlespinasse/git-commit-data-action/1.1.1/entrypoint.sh
Error: Unable to process file command 'env' successfully.
Error: Invalid environment variable value. Matching delimiter not found 'EOF'
```

This is the action
```
      - name: Expose git commit data
        uses: rlespinasse/git-commit-data-action@1.1.1
```

Here's the failing run:
https://github.com/yoavain/easylists-for-pihole/runs/2153199930?check_suite_focus=true

**Comment by rlespinasse** [comment]
I have reproduce this bug once, and now, all my other tests can't reproduce it. Strange behavior.
I also put a repository to experiment with this issue https://github.com/rlespinasse/gcda-issue-11

As expected, when a commit have multiple lines in the body, the v1.1.1 do the job and the v1.1.0 fail.
The v1.1.0 don't fail when the body have only one line (like your case).

I will keep investigate that behavior.

**Comment by rlespinasse** [comment]
I finally reproduce the issue and found the bug.
The end delimiter wasn't setup correctly due to missing newline character.

Feel free to reopen this issue if the fix is not enough for your use case.
